### ISSUE TITLE
Issues if run the tool from Debian

### ISSUE THREAD

**Issue by D-Kalinin** [feeltheajf/trufflehog3#36] opened 2021-11-12 21:38 UTC
Hey on Debian the tool is working weird or i am doing something wrong. ( we are using tool within docker file and installing from apt-get)
First of all i using your tool on Redhat too, and there tool is working, but
on Redhat when i doing trufflehog3 --help i see next:
usage: trufflehog3 [options] source

Find secrets in your codebase.

positional arguments:
  source             URLs or paths to local folders for secret searching

optional arguments:
  -h, --help         show this help message and exit
  -v, --verbose      enable verbose logging {-v, -vv, -vvv}
  -c, --config       path to config file
  -o, --output       write report to file
  -f, --format       output format {text, json, yaml, html}
  -r, --rules        ignore default regexes and source from file
  -R, --render-html  render HTML report from JSON or YAML
  --branch           name of the repository branch to be scanned
  --since-commit     scan starting from a given commit hash
  --skip-strings     skip matching strings
  --skip-paths       skip paths matching regex
  --line-numbers     include line numbers in match
  --max-depth        max commit depth for searching
  --no-regex         disable high signal regex checks
  --no-entropy       disable entropy checks
  --no-history       disable commit history check
  --no-current       disable current status check

 ------------------------------------------
 And this absolutely different when i do same command in Debian, there next results:
 usage: trufflehog3 [arguments] targets

Find secrets in your codebase

positional arguments:
  targets                 Search targets, defaults to current directory

optional arguments:
  -h, --help              show this help message and exit
  -z, --zero              always exit with zero status code
  -v, --verbose           enable verbose logging {-v, -vv, -vvv}
  -o, --output file       path to output file
  -c, --config file       path to config file
  -r, --rules file        path to rules file
  -i, --incremental file  path to previous scan
  -p, --processes int     number of subprocesses to run (8)

search arguments:
  -e, --exclude str       exclude matching issues
  -s, --severity {LOW, MEDIUM, HIGH}
                          minimum severity filter (LOW)
  --ignore-nosecret       ignore inline 'nosecret' annotations
  --no-entropy            disable entropy checks
  --no-pattern            disable pattern checks

source arguments:
  --branch str            name of the repo branch to scan
  --depth int             max commits depth for searching (10000)
  --since                 scan from the given commit hash
  --no-current            disable current status check
  --no-history            disable commit history check

render arguments:
  -f, --format {TEXT, JSON, HTML}
                          output format (TEXT)
  --context int           number of context lines to include

other commands:
  -R, --render-html       render HTML report from JSON
  -V, --version           show version message and exit

learn more:
  https://github.com/feeltheajf/trufflehog3

version:
  3.0.3
  -----------------------------------------
  Issue is when i running trufflehog3 scan on Debian, i do not have any results, nothing , and as i understand arguments are different on Redhat and Debian:
  I running next command on Redhat and it works:
${TRUFFLEHOG_HOME} https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.org.gov/${ORGNAME}/${JOB_NAME}.git --skip-string "SOME STRING" --skip-paths "SOME PATHS" -o ${JOB_NAME}.json -f json

 I running next command on Debian and its not working:
 ${TRUFFLEHOG_HOME} --depth 1000 --exclude "SOME STRING" https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.org.gov/${ORGNAME}/${JOB_NAME}.git -o ${JOB_NAME}.json -f json
 No errors, json file just empty, same with html report, and html report generated from Redhat and from Debian are different by style, but on the bottom trufflehog3 link ...
So , the question is, what am i doing wrong on Debian, why arguments are different in Redhat and Debian?

 Another question, in Redhat as you can see i using --skip-paths and --skip-string arguments, in Debian i see only --exclude argument , which means exclude just strings, not paths. How can i exclude paths too? Maybe i can save all strings and paths and just give a path to the file and do not show what exactly i want to exclude in my request?

 Thank you.

**Comment by feeltheajf** [comment] 2021-11-12 23:55
hi @RepositoryOfCode 

I believe the issue is not related to Debian. You are using different versions of trufflehog, the one on CentOS is quite outdated. The latest trufflehog versions require python 3.7 or higher which is not available by default on CentOS. You can check the currently installed version by running 

```
pip freeze | grep -i trufflehog3
```

After that you can install the same trufflehog version on Debian if you prefer. Hope this clarifies

**Comment by D-Kalinin** [comment] 2021-11-15 14:11
Thank you for answer.
I do no not have issue with RedHat (you mentioned Centos) , my issue on Debian, 
I was running pip freeze | grep -i trufflehog3 on Debian and saw trufflehog3==3.0.3, as i understand its last and correct version.
But i still can not scan, when i trying to scan something, i do not have results at all, nothing, no errors even, no response, json file is empty.
And as i asked before how can i manage false positive? Before you had --skip-path, --skip-string, now i see another argument --exclude, but its for strings, whats argument for path? And can i save all false positives in file and then just give a path to it? But what argument i have to use?
Anyway , first i need help how to get response after scan, in my first comment the request what i sending is correct? Maybe something wrong in request (i was trying scan your repo too, and same, no results)

**Comment by D-Kalinin** [comment] 2021-11-15 14:41
I have noticed, that i using trufflehog3 version 2.0.7 on RedHat and it works perfectly.
How can I install 2.0.7 version on Debian instead of 3.0.3 version? I need python 3.6 version for that? Or maybe you can explain what i am doing wrong with 3.0.3 version, why I do not get any scan results?

**Comment by D-Kalinin** [comment] 2021-11-15 15:19
I have fixed it.
Thanks again.
Installed on Debian 2.07 version instead of 3.0.3.
But still have a question, why 3.0.3 does not return results?

**Comment by feeltheajf** [comment] 2021-11-15 15:51
> Before you had --skip-path, --skip-string, now i see another argument --exclude, but its for strings, whats argument for path?

I'd suggest to start with README, a lot has changed since 2.0.2 you're currently using. After that, check out the `.trufflehog3.yml` in this repository. 

> Installed on Debian 2.07 version instead of 3.0.3.
But still have a question, why 3.0.3 does not return results?

I don't think I can answer this, since the repo you're scanning is private. Can you show an example with some public repo? Meanwhile, I'll try to compare them as well. It's important to understand if v3 is missing something

**Comment by D-Kalinin** [comment] 2021-11-15 18:40
I was trying scan and public repos too, even your repo, no results.

**Comment by all3njk** [comment] 2021-11-29 19:24
I am also facing the same issue in Pop OS Linux debian.

**Comment by feeltheajf** [comment] 2021-12-08 22:03
@RepositoryOfCode @jxa123 

While it is expected that trufflehog3 repo scan should not return any issues due to the exclude config, there was indeed a bug with remote repositories. I believe this should be fixed in v3.0.4 now.

**Comment by bitanshu** [comment] 2021-12-14 05:53
Was the issue with --skip-paths addressed in 3.0.4?
I was using the versin 3.0.4 but still i receive error saying that unrecognised arguments when using --skip-paths.
Do i have any way to exclude all the files ending in .dbc with exclude?

**Comment by feeltheajf** [comment] 2021-12-17 15:10
v3 does not have such option. Please check out the README for config and exclude options

**Closed as completed** 2022-02-05 06:26 UTC
